Section "Device"
    Identifier  "Mali G610"
    Driver      "modesetting"
    Option      "kmsdev" "/dev/dri/card0"
    Option      "Monitor-HDMI-2" "HDMI2"
EndSection

Section "Monitor"
    Identifier  "HDMI2"
EndSection

Section "Screen"
    Identifier  "Screen0"
    Device      "Mali G610"
    Monitor     "HDMI2"
    DefaultDepth 24
EndSection